name: DVC Pull from GCS

on:
  push:
    branches:
      - main  # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull request to the 'main' branch

jobs:
  dvc-pull:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Set up Python to use DVC
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # You can specify the required Python version here

      # Install DVC and the GCS dependency
      - name: Install DVC with GCS support
        run: |
          python -m pip install --upgrade pip
          pip install dvc[gs]  # Install DVC with GCS support

      # Authenticate Google Cloud with the service account
      - name: Set up Google Cloud credentials
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo $GOOGLE_APPLICATION_CREDENTIALS > /tmp/gcloud-service-key.json
          gcloud auth activate-service-account --key-file=/tmp/gcloud-service-key.json
          gcloud config set project your-gcp-project-id

      # Pull the data from the GCS bucket using DVC
      - name: DVC Pull
        run: |
          dvc pull -v

