name: Retrain Model on DVC Data Changes

on:
  push:
    branches:
      - main

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up DVC
      - name: Set up DVC
        uses: iterative/setup-dvc@v1
        with:
          version: 'latest'

      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11.5'

      # Step 4: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 5: Check DVC remote configuration
      - name: Check DVC remote configuration
        run: |
          dvc remote list  # List current remotes for verification

      # Step 6: Pull the latest data version using DVC
     # - name: DVC Pull latest data
     #   run: |
      #    dvc pull -v || (echo "DVC pull failed. Ensure the data is available in the DVC remote." && exit 1)

      # Step 7: Run the training script
      - name: Run training script
        run: |
          python main.py
